[meta]
name = "Clear-Tec-Balls"
version = "1.0.9"
author = "CryT4x"
description = "Includes 2 Balls: Clear, Dots | and 1 Hat: Coors"
min_host = "0.8.0"
dependencies = ["cosmetic-kit"]

[script]
files = ["main.as"]
assets = ["*.png", "models/*.txt"]
